<?php

function fish_catch_block_info()
{
	$blocks['fish_catch'] = array(
		'info'  => t('Fish catch'),
		'cache' => DRUPAL_CACHE_PER_ROLE, // по умолчанию
	);

	return $blocks;
}

function fish_catch_menu()
{

	$items = array();

	$items['admin/config/content/fish_catch'] = array(
		'title'            => 'Рыболовная фирма',
		'description'      => 'Управление информацией.',
		'page callback'    => 'fish_list',
		'access arguments' => array('administer site configuration'),
	);

    // список катеров
    $items['admin/config/content/fish_catch/list'] = array(
        'title'  => 'Катеры',
        'type'   => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 1,
    );
    // добавление рейса
    $items['admin/config/content/fish_catch/passport/%passport_cruise/cruise'] = array(
        'title'            => 'Добавить рейс',
        'page callback'    => 'drupal_get_form',
        'page arguments'   => array('fish_catch_passport_cruise_form', 5),
        'access arguments' => array('administer site configuration'),
        'type'             => MENU_CALLBACK,
    );
    // члены команды
    $items['admin/config/content/fish_catch/crewman/list'] = array(
        'title'            => 'Члены команды',
        'page callback'    => 'fish_crewman_list',
        'access arguments' => array('administer site configuration'),
        'type'             => MENU_LOCAL_TASK,
        'weight'           => 3,
    );
    // члены команды рейса
    $items['admin/config/content/fish_catch/cruise/%cruise_crewteam/cruise_team'] = array(
        'title'            => 'Члены команды',
        'page arguments'   => array(5),
        'page callback'    => 'fish_cruise_team_list',
        'access arguments' => array('administer site configuration'),
        'type'             => MENU_CALLBACK,
    );


    return $items;
}



// список рейсов
function fish_list()
{
	$header = array(
		array('data' => t('Name')),
		array('data' => t('Release_date')),
		array('data' => t('Fishes')),
		array('data' => t('Actions')),
	);

    $query = db_query("SELECT c.cruise_id, c.passport_id, c.release_date, p.name, 
          (SELECT COUNT(f.fish_id) AS count FROM {fish} AS f WHERE f.cruise_id = c.cruise_id) AS count
          FROM {passport} AS p, {cruise} AS c WHERE p.passport_id = c.passport_id", array());
    $result = $query->fetchAll();

    $row = array();

    if($result) {
        foreach ($result as $item) {
            $actions = array(
                l(t('add cruise'), 'admin/config/content/fish_catch/passport/' . $item->passport_id . '/cruise'),
                l(t('crewmans'), 'admin/config/content/fish_catch/cruise/' . $item->cruise_id . '/cruise_team'),
            );

            $date = date('d-m-Y', $item->release_date);
            $row [] = array(
                array('data' => $item->name),
                array('data' => $date),
                array('data' => $item->count),
                array('data' => implode(' | ', $actions)),
            );
        }
    }

	return theme('table', array(
		'header' => $header,
		'rows'   => $row,
	));
}






// добавление рейса
function fish_catch_passport_cruise_form($form, &$form_state, $passport_cruise = null)
{

    $form['passport_id'] = array(
        '#title'         => t('Passport id'),
        '#description'   => t('Insert passport id'),
        '#type'          => 'textfield',
        '#default_value' => $passport_cruise ? $passport_cruise : '',
        '#required'      => true,
    );
    $form['release_date'] = array(
        '#title'         => t('Release date'),
        '#description'   => t('Release date 22-03-2018'),
        '#type'          => 'textfield',
        '#default_value' => '',
        '#required'      => true,
    );
    $form['return_date'] = array(
        '#title'         => t('Return date'),
        '#description'   => t('Return date 22-03-2018'),
        '#type'          => 'textfield',
        '#default_value' => '',
        '#required'      => false,
    );

    $form['submit'] = array(
        '#type'  => 'submit',
        '#value' => $passport_cruise ? t('Save') : t('Add'),
    );

    return $form;
}

function fish_catch_passport_cruise_form_validate($form, &$form_state)
{

}

function fish_catch_passport_cruise_form_submit($form, &$form_state)
{
    $addData = array(
        'passport_id' => $form_state['values']['passport_id'],
        'release_date' => $form_state['values']['release_date'],
        'return_date' => $form_state['values']['return_date'],
    );

    // formating date to int
    $addData['release_date'] = strtotime($addData['release_date']);
    $addData['return_date'] = strtotime($addData['return_date']);

    drupal_write_record('cruise', $addData);
    drupal_set_message(t('cruise added!'));

    drupal_goto('admin/config/content/fish_catch');
}




// редактирование рейса
function fish_catch_cruise_form($form, &$form_state, $cruise_info = null)
{

    $form['passport_id'] = array(
        '#title'         => t('Passport id'),
        '#description'   => t('Insert passport id'),
        '#type'          => 'textfield',
        '#default_value' => $cruise_info ? $cruise_info['passport_id'] : '',
        '#required'      => true,
    );
    $form['release_date'] = array(
        '#title'         => t('Release date'),
        '#description'   => t('Release date 22-03-2018'),
        '#type'          => 'textfield',
        '#default_value' => $cruise_info ? date('d-m-Y', $cruise_info['release_date']) : '',
        '#required'      => true,
    );
    $form['return_date'] = array(
        '#title'         => t('Return date'),
        '#description'   => t('Return date 22-03-2018'),
        '#type'          => 'textfield',
        '#default_value' => $cruise_info ? date('d-m-Y', $cruise_info['return_date']) : '',
        '#required'      => false,
    );

    $form['submit'] = array(
        '#type'  => 'submit',
        '#value' => $cruise_info ? t('Save') : t('Add'),
    );

    if ($cruise_info) {
        $form['cruise_id'] = array(
            '#type'  => 'value',
            '#value' => $cruise_info['cruise_id'],
        );
    }
    return $form;
}

function fish_catch_cruise_form_validate($form, &$form_state)
{

}

function fish_catch_cruise_form_submit($form, &$form_state)
{
    $addData = array(
        'passport_id' => $form_state['values']['passport_id'],
        'release_date' => $form_state['values']['release_date'],
        'return_date' => $form_state['values']['return_date'],
    );

    // formating date to int
    $addData['release_date'] = strtotime($addData['release_date']);
    $addData['return_date'] = strtotime($addData['return_date']);

    // save edit data
    if (isset($form_state['values']['cruise_id'])) {
        $addData['cruise_id'] = $form_state['values']['cruise_id'];
        drupal_write_record('cruise', $addData, 'cruise_id');
        drupal_set_message(t('cruise saved!'));
    } // add new data
    else {
        drupal_write_record('cruise', $addData);
        drupal_set_message(t('cruise added!'));
    }

    drupal_goto('admin/config/content/fish_catch');
}


function cruise_info_load($id)
{
    $cruise_info = db_select('cruise', 'n')
        ->fields('n', array('cruise_id', 'passport_id', 'release_date', 'return_date'))
        ->condition('n.cruise_id', $id)
        ->execute()->fetchAssoc();

    return $cruise_info;
}





// члены команды
function fish_crewman_list()
{
    $header = array(
        array('data' => t('Name')),
        array('data' => t('Post')),
        array('data' => t('Address')),
        array('data' => t('Actions'))
    );

    $query = db_query("SELECT * FROM {crewman}", array());
    $result = $query->fetchAll();

    $row = array();

    if($result) {
        foreach ($result as $item) {
            $actions = array(
                l(t('add in cruiseteam'), 'admin/config/content/fish_catch/cruise_team/' . $item->crewman_id . '/crewman'),
            );

            $row [] = array(
                array('data' => $item->name),
                array('data' => $item->address),
                array('data' => $item->post),
                array('data' => implode(' | ', $actions)),
            );
        }
    }

    return theme('table', array(
        'header' => $header,
        'rows'   => $row,
    ));
}




// члены команды рейса
function fish_cruise_team_list($cruise_crewteam)
{
    print_r($cruise_crewteam);

    $header = array(
        array('data' => t('Name')),
        array('data' => t('Post')),
        array('data' => t('Address')),
        array('data' => t('Actions'))
    );

    $query = db_query("SELECT m.crewman_id, m.name, m.address, m.post FROM {crewman} AS m,
          {cruise_team} AS t, {cruise} AS c
          WHERE c.cruise_id = :cid AND c.cruise_id = t.cruise_id AND t.crewman_id = m.crewman_id",
        array("cid" => $cruise_crewteam));
    $result = $query->fetchAll();

    $row = array();

    if($result) {
        foreach ($result as $item) {
            $actions = array(
                l(t('delete'), 'admin/config/content/fish_catch/cruise/crewman/' . $item->crewman_id . '/delete'),
            );

            $row [] = array(
                array('data' => $item->name),
                array('data' => $item->address),
                array('data' => $item->post),
                array('data' => implode(' | ', $actions)),
            );
        }
    }

    return theme('table', array(
        'header' => $header,
        'rows'   => $row,
    ));
}